version: "3"

services:
  db:
    container_name: squid_db
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    shm_size: 1gb
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    volumes:
     - data_staking_db:/var/lib/postgresql/data

  api:
    image: ${SQUID_IMAGE_NAME:-staking_squid:latest}
    environment:
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - GQL_PORT=4350
    ports:
      # GraphQL endpoint at port 4350
      - "${GQL_PORT}:4350"
    command: ["sqd", "serve:prod"]
    depends_on:
      - db

  processor:
    image: ${SQUID_IMAGE_NAME:-staking_squid:latest}
    environment:
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
    ports:
      # prometheus metrics exposed at port 3000
      - "${PROCESSOR_PROMETHEUS_PORT}:3000"
    command: ["sqd", "process:prod"]
    depends_on:
      - db

volumes:
  data_staking_db: